name: Conan Publish
author: Alexandr Timofeev <alexandr.p.timofeev@gmail.com>
description: An action to automatically create pull requests for the https://github.com/conan-io/conan-center-index

inputs:
  github_token:
    description: GitHub token secret
    required: true

runs:
  using: "node12"
  main: "index.js"
